// Canonical metadata for every table the admin Database page can browse.
// Mirrors backend/models/*.js in the main LumoraClear repo (see the
// schemas.ts reference the admin site was designed against). Kept as static
// metadata (rather than pure information_schema introspection) so nullability,
// FK targets, and column purpose read the same as the Sequelize models —
// update this file by hand if a model changes.
//
// `tableName` is the literal Postgres table name and is the ONLY value ever
// interpolated into a SQL identifier — always resolve it by looking up a
// `key` in TABLES below, never by using client-supplied text directly.

export const TABLES = [
  {
    key: "users",
    tableName: "users",
    displayName: "Users",
    primaryKey: "id",
    description: "Application accounts (password and/or social login).",
    columns: [
      { name: "id", type: "integer", nullable: false },
      { name: "first_name_id", type: "integer", nullable: true, fk: "encryptedobject.id" },
      { name: "last_name_id", type: "integer", nullable: true, fk: "encryptedobject.id" },
      { name: "email_id", type: "integer", nullable: false, fk: "encryptedobject.id" },
      { name: "email_hash", type: "string", nullable: false, description: "sha256-ish hash of email, for lookups" },
      { name: "passwordHash", type: "string", nullable: true, description: "null for social-login-only accounts" },
      { name: "phone_number_id", type: "integer", nullable: true, fk: "encryptedobject.id" },
      { name: "phone_number_hash", type: "string", nullable: true },
      { name: "dob_id", type: "integer", nullable: true, fk: "encryptedobject.id" },
      { name: "google_sub", type: "string", nullable: true, description: "unique" },
      { name: "microsoft_oid", type: "string", nullable: true, description: "unique" },
      { name: "apple_sub", type: "string", nullable: true, description: "unique" },
      { name: "role", type: "string", nullable: false, description: "default 'user'; also 'Admin' | 'Developer'" },
      { name: "email_notifications", type: "boolean", nullable: false, description: "default true" },
      { name: "push_notifications", type: "boolean", nullable: false, description: "default true" },
      { name: "push_token", type: "string", nullable: true, description: "Expo push token" },
    ],
  },
  {
    key: "encryptedobject",
    tableName: "encryptedobject",
    displayName: "Encrypted Objects",
    primaryKey: "id",
    description: "AES-256-GCM encrypted values referenced by *_id columns elsewhere.",
    columns: [
      { name: "id", type: "integer", nullable: false },
      { name: "encrypted", type: "string", nullable: false, description: "ciphertext" },
      { name: "iv", type: "string", nullable: false },
      { name: "tag", type: "string", nullable: false, description: "AES-GCM auth tag" },
      { name: "created_at", type: "timestamp", nullable: false },
    ],
  },
  {
    key: "eligibility",
    tableName: "eligibility",
    displayName: "Eligibility",
    primaryKey: "eligibility_id",
    description: "Insurance coverage records. Unique on (user_id, member_id_hash).",
    columns: [
      { name: "eligibility_id", type: "integer", nullable: false },
      { name: "user_id", type: "integer", nullable: false, fk: "users.id (CASCADE)" },
      { name: "insurance_company_id", type: "integer", nullable: false, fk: "encryptedobject.id (CASCADE)" },
      { name: "member_id_id", type: "integer", nullable: false, fk: "encryptedobject.id (CASCADE)" },
      { name: "member_id_hash", type: "string", nullable: false },
      { name: "plan_type_id", type: "integer", nullable: false, fk: "encryptedobject.id (CASCADE)" },
      { name: "coverage_start", type: "date", nullable: false },
      { name: "coverage_end", type: "date", nullable: false },
      { name: "created_at", type: "timestamp", nullable: false },
      { name: "updated_at", type: "timestamp", nullable: false },
    ],
  },
  {
    key: "billing",
    tableName: "billing",
    displayName: "Billing (synced EOBs)",
    primaryKey: "bill_id",
    description: "One row per synced EOB from a payer sync. Distinct from bill_uploaded.",
    columns: [
      { name: "bill_id", type: "integer", nullable: false },
      { name: "eligibility_id", type: "integer", nullable: false, fk: "eligibility.eligibility_id (CASCADE)" },
      { name: "date_of_service", type: "date", nullable: false },
      { name: "bill_date", type: "date", nullable: false },
      { name: "due_date", type: "date", nullable: false },
      { name: "total_charged", type: "decimal(10,2)", nullable: false },
      { name: "amount_charged", type: "decimal(10,2)", nullable: false },
      { name: "insurance_coverage", type: "decimal(10,2)", nullable: false, description: "default 0" },
      { name: "payment_status", type: "string", nullable: false, description: "default 'pending'" },
      { name: "in_network", type: "string", nullable: false, description: "'true' | 'false' (stored as string)" },
      { name: "location", type: "string", nullable: false },
      { name: "service_description_id", type: "integer", nullable: true, fk: "encryptedobject.id (SET NULL)" },
      { name: "notes_id", type: "integer", nullable: true, fk: "encryptedobject.id (SET NULL)" },
      { name: "has_error", type: "boolean", nullable: false, description: "default false" },
      { name: "external_id", type: "string", nullable: true, description: "unique — insurer's EOB id, for dedup" },
      { name: "billable_period_start", type: "date", nullable: true },
      { name: "billable_period_end", type: "date", nullable: true },
      { name: "created_at", type: "timestamp", nullable: false },
      { name: "updated_at", type: "timestamp", nullable: false },
    ],
  },
  {
    key: "bill_uploaded",
    tableName: "bill_uploaded",
    displayName: "Bill Uploads",
    primaryKey: "id",
    description: "A user-uploaded bill photo + vision-extraction result + match outcome.",
    columns: [
      { name: "id", type: "integer", nullable: false },
      { name: "user_id", type: "integer", nullable: false, fk: "users.id (CASCADE)" },
      { name: "coverage_id", type: "integer", nullable: true, fk: "eligibility.eligibility_id (SET NULL)" },
      { name: "eob_id", type: "integer", nullable: true, fk: "billing.bill_id (SET NULL)" },
      { name: "match_status", type: "string", nullable: false, description: "'matched' | 'unmatched', default 'unmatched'" },
      { name: "patient_name_id", type: "integer", nullable: true, fk: "encryptedobject.id (SET NULL)" },
      { name: "service_description_id", type: "integer", nullable: true, fk: "encryptedobject.id (SET NULL)" },
      { name: "account_number", type: "string", nullable: true },
      { name: "date_of_service", type: "date", nullable: true },
      { name: "bill_date", type: "date", nullable: true },
      { name: "due_date", type: "date", nullable: true },
      { name: "amount_charged", type: "decimal(10,2)", nullable: true },
      { name: "total_charged", type: "decimal(10,2)", nullable: true },
      { name: "location", type: "string", nullable: true },
      { name: "in_network", type: "string", nullable: true },
      { name: "raw_extraction", type: "text", nullable: true, description: "raw JSON string from the vision model" },
      { name: "created_at", type: "timestamp", nullable: false },
      { name: "updated_at", type: "timestamp", nullable: false },
    ],
  },
  {
    key: "benefits",
    tableName: "benefits",
    displayName: "Benefits",
    primaryKey: "benefit_id",
    columns: [
      { name: "benefit_id", type: "integer", nullable: false },
      { name: "eligibility_id", type: "integer", nullable: false, fk: "eligibility.eligibility_id (CASCADE)" },
      { name: "benefit_name", type: "string", nullable: false },
      { name: "coverage_level", type: "string", nullable: true },
      { name: "amount", type: "decimal(10,2)", nullable: true },
      { name: "remaining", type: "decimal(10,2)", nullable: true },
      { name: "in_network", type: "string", nullable: false },
    ],
  },
  {
    key: "benefit_services",
    tableName: "benefit_services",
    displayName: "Benefit Services",
    primaryKey: "service_id",
    columns: [
      { name: "service_id", type: "integer", nullable: false },
      { name: "benefit_id", type: "integer", nullable: false, fk: "benefits.benefit_id (CASCADE)" },
      { name: "service_name", type: "string", nullable: true },
    ],
  },
  {
    key: "sync_jobs",
    tableName: "sync_jobs",
    displayName: "Sync Jobs",
    primaryKey: "id",
    description: "Background payer-sync queue (coverage + eob jobs).",
    columns: [
      { name: "id", type: "integer", nullable: false },
      { name: "user_id", type: "integer", nullable: false, fk: "users.id (CASCADE)" },
      { name: "provider", type: "string", nullable: false, description: "'cigna' | 'unitedHealthcare' | 'aetna' | 'ambetter'" },
      { name: "job_type", type: "string", nullable: false, description: "'coverage' | 'eob'" },
      { name: "status", type: "string", nullable: false, description: "'queued' | 'processing' | 'done' | 'failed'" },
      { name: "access_token_enc", type: "string", nullable: true, description: "encrypted FHIR bearer token, cleared once done" },
      { name: "patient_id", type: "string", nullable: true },
      { name: "eligibility_id", type: "integer", nullable: true, fk: "eligibility.eligibility_id (CASCADE)" },
      { name: "total_items", type: "integer", nullable: true },
      { name: "completed_items", type: "integer", nullable: false, description: "default 0" },
      { name: "is_new_plan", type: "boolean", nullable: true, description: "set on 'eob' jobs created by a 'coverage' job" },
      { name: "error_message", type: "string", nullable: true },
      { name: "created_at", type: "timestamp", nullable: false },
      { name: "updated_at", type: "timestamp", nullable: false },
    ],
  },
  {
    key: "user_otp",
    tableName: "user_otp",
    displayName: "User OTPs",
    primaryKey: "id",
    description: "Exactly one of phone_number_hash/email_hash is set per row.",
    columns: [
      { name: "id", type: "integer", nullable: false },
      { name: "user_id", type: "integer", nullable: true, fk: "users.id (CASCADE)", description: "not currently populated by /send-otp" },
      { name: "phone_number_hash", type: "string", nullable: true },
      { name: "email_hash", type: "string", nullable: true },
      { name: "otp_hash", type: "string", nullable: false },
      { name: "expires_at", type: "timestamp", nullable: false },
      { name: "used", type: "boolean", nullable: false, description: "default false" },
      { name: "reset_token", type: "string", nullable: true, description: "set once OTP verified, step:'forgot'" },
      { name: "reset_token_expires_at", type: "timestamp", nullable: true },
      { name: "created_at", type: "timestamp", nullable: false },
    ],
  },
  {
    key: "tempotp",
    tableName: "tempotp",
    displayName: "Temp Registration OTPs",
    primaryKey: "id",
    description: "Holds pending-registration data until /complete-register creates a real User row.",
    columns: [
      { name: "id", type: "integer", nullable: false },
      { name: "first_name_id", type: "integer", nullable: false, fk: "encryptedobject.id" },
      { name: "last_name_id", type: "integer", nullable: false, fk: "encryptedobject.id" },
      { name: "email_id", type: "integer", nullable: false, fk: "encryptedobject.id" },
      { name: "password_id", type: "integer", nullable: false, fk: "encryptedobject.id" },
      { name: "phone_number_id", type: "integer", nullable: false, fk: "encryptedobject.id" },
      { name: "dob_id", type: "integer", nullable: false, fk: "encryptedobject.id" },
      { name: "expires_at", type: "timestamp", nullable: false },
      { name: "used", type: "boolean", nullable: false, description: "default false" },
    ],
  },
  {
    key: "sessions",
    tableName: "sessions",
    displayName: "Sessions",
    primaryKey: "id",
    columns: [
      { name: "id", type: "integer", nullable: false },
      { name: "user_id", type: "integer", nullable: false, fk: "users.id (CASCADE)" },
      { name: "session_token", type: "string", nullable: false, description: "unique" },
      { name: "ip_address", type: "string", nullable: true },
      { name: "user_agent", type: "string", nullable: true },
      { name: "expires_at", type: "timestamp", nullable: false },
      { name: "last_activity", type: "timestamp", nullable: false },
      { name: "created_at", type: "timestamp", nullable: false },
    ],
  },
  {
    key: "audit_logs",
    tableName: "audit_logs",
    displayName: "Audit Logs",
    primaryKey: "id",
    columns: [
      { name: "id", type: "integer", nullable: false },
      { name: "user_id", type: "integer", nullable: true, fk: "users.id" },
      { name: "action", type: "string", nullable: false, description: "e.g. 'PLAN_DELETED', 'PASSWORD_UPDATED', ..." },
      { name: "target_type", type: "string", nullable: true },
      { name: "target_id", type: "integer", nullable: true },
      { name: "ip_address", type: "string", nullable: true },
      { name: "user_agent", type: "string", nullable: true },
      { name: "success", type: "boolean", nullable: false, description: "default true" },
      { name: "error_message", type: "string", nullable: true },
      { name: "notes", type: "string", nullable: true },
      { name: "timestamp", type: "timestamp", nullable: false, description: "createdAt column" },
    ],
  },
  {
    key: "theme_colors",
    tableName: "theme_colors",
    displayName: "Theme Colors",
    primaryKey: "mode",
    description: "Live-editable theme, also managed via the Color Scheme page.",
    columns: [
      { name: "mode", type: "string", nullable: false, description: "'light' | 'dark', primary key" },
      { name: "background", type: "string", nullable: false },
      { name: "secondaryBackground", type: "string", nullable: false },
      { name: "boxBackground", type: "string", nullable: false },
      { name: "text", type: "string", nullable: false },
      { name: "secondaryText", type: "string", nullable: false },
      { name: "invertText", type: "string", nullable: false },
      { name: "tint", type: "string", nullable: false },
      { name: "buttonColor", type: "string", nullable: false },
      { name: "baseColor", type: "string", nullable: false },
      { name: "error", type: "string", nullable: false },
      { name: "errorLightLight", type: "string", nullable: false },
      { name: "pending", type: "string", nullable: false },
      { name: "paid", type: "string", nullable: false },
      { name: "shadow", type: "string", nullable: false },
      { name: "updated_at", type: "timestamp", nullable: false },
    ],
  },
];

export function getTableByKey(key) {
  return TABLES.find((t) => t.key === key);
}
